#!/bin/sh

RED='\033[0;31m'
YELLOW='\033[0;33m'
NC='\033[0m'

CA_CERTIFICATES_PATH="/usr/local/share/ca-certificates/ca.crt"
if [ -f "${CA_CERTIFICATES_PATH}" ]; then
  echo "Updating CA certificates..."
  update-ca-certificates --fresh >/dev/null
fi

if [ -z "$URL" ]; then
  printf "${RED}ERROR: \$URL is not defined, exiting${NC}\n"
  exit 1
fi

if [ -z "$TOKEN" ]; then
  printf "${RED}ERROR: \$TOKEN is not defined, exiting${NC}\n"
  exit 1
fi

if [ -z "$NAME" ]; then
  printf "${RED}ERROR: \$NAME is not defined, exiting${NC}\n"
  exit 1
fi

DOCKER_PRIVILEGED=""
DOCKER_VOLUME_DOCKER_SOCKET=""
DOCKER_VOLUME_ZONEINFO=""
if [ "$PRIVILEGED" == "true" ]; then
  DOCKER_PRIVILEGED="--docker-privileged"
fi
if [ "$SHARE_DOCKER_SOCKET" == "true" ]; then
  DOCKER_VOLUME_DOCKER_SOCKET='--docker-volumes=/var/run/docker.sock:/var/run/docker.sock'
fi
if [ "$SHARE_ZONEINFO" == "true" ] && [ -n "$TZ" ]; then
  DOCKER_VOLUME_ZONEINFO='--docker-volumes=/usr/share/zoneinfo:/usr/share/zoneinfo:ro'
fi

ENV_TZ=""
if [ -n "$TZ" ]; then
  ENV_TZ="--env=$TZ"
fi

unregister_all_runners() {
  echo "Unregister and stop all runners..."
  if [ -f /etc/gitlab-runner/config.toml ]; then
    for n in `cat /etc/gitlab-runner/config.toml | grep -Eo 'name = "(.*)"' | cut -d= -f2 | cut -d\" -f2`; do
      echo "Unregister runner $n..."
      gitlab-runner unregister --name $n
    done
  fi
}

_term() {
  unregister_all_runners
  unregister_exit_code="$?"

  # terminate `gitlab-runner run` command
  kill -TERM "$gitlab_runner_pid"

  if [ "$unregister_exit_code" -ne "0" ]; then
    echo "Unregister failed"
    exit $unregister_exit_code
  else
    exit 0
  fi
}

trap _term TERM INT QUIT

unregister_all_runners

echo "Register new runner $NAME"
gitlab-runner register \
    --non-interactive \
    --url="$URL" \
    --registration-token="$TOKEN" \
    --tag-list="$TAG_LIST" \
    --name="$NAME" \
    --executor="docker" \
    --docker-image="$DOCKER_IMAGE" \
    $DOCKER_PRIVILEGED \
    $DOCKER_VOLUME_DOCKER_SOCKET \
    $DOCKER_VOLUME_ZONEINFO \
    --locked=${LOCKED:-false} \
    $ADDITIONAL_OPTIONS

# exit if `gitlab-runner register` returned exit code != 0
if [ "$?" -ne "0" ]; then
  exit "$?"
fi

echo "Generated config file:"
printf $YELLOW
cat /etc/gitlab-runner/config.toml
printf $NC

echo "Running runner..."
gitlab-runner run &
gitlab_runner_pid=$!
wait "$gitlab_runner_pid"
